LEVELS = application.csv arithmetic.csv booleans-definition.csv               \
    booleans-intro.csv define-challenges.csv definition.csv\
    functions-challenge.csv functions.csv higher-order-functions.csv          \
    multiargument.csv recursion-basics.csv recursion-higher-order.csv         \
    replication.csv testing.csv weekdays.csv lists-intro.csv lists-query.csv \
    play.csv list-basics.csv list-counting.csv list-filtering.csv lists-pair.csv \
    lists-mapping.csv strings.csv list-sorting.csv letExpr.csv

VPATH = levels:

levels_built: $(LEVELS)
	./build.sh levels
	@touch levels_built
