#!/bin/bash

target="reduct-web"

for d in "../reduct-web" "${HOME}/reduct-web"
do
    if [[ ! -d "$target/.git" ]]
    then
        target="$d"
    fi
done
if [[ ! -d "$target/.git" ]]
then
    echo "Can't find reduct-web directory to target"
    exit 1
fi

rm -rf dist .cache
if [[ ! -d dist ]]
then
    mkdir dist
fi

if [[ -x `which yarn` ]]
then
    yarn dist
elif [[ -x `which npm` ]]
then
    npm run dist
else
    echo "Can't find yarn or npm"
fi

ln -s ../resources dist/resources

rsync -Lr dist/ "$target"/
echo "Target $target updated. Use git add/git commit/git push to push updates"
