levels:
  - board:
      - (number => number)(1)
    goal:
      - 1
    toolbox: []
    defines: []
    globals: {}
    textgoal: Use the application block
    note: null
    hiddenGlobals: []
    syntax: []
    autograder:
      inputs: []
      outputs: []
  - board:
      - (x => x + 1)(_)
      - (x => x)(_)
    goal:
      - 4
    toolbox:
      - 2
      - 3
      - 4
    defines: []
    globals: {}
    textgoal: ''
    note: null
    hiddenGlobals: []
    syntax: []
    autograder:
      inputs: []
      outputs: []
  - board:
      - _(5)
      - _(3)
      - _(8)
    goal:
      - 1
      - 6
      - 8
    toolbox:
      - x => x + 1
      - x => x - 2
      - x => x
      - x => x + 3
    defines: []
    globals: {}
    textgoal: ''
    note: null
    hiddenGlobals: []
    syntax: []
    autograder:
      inputs: []
      outputs: []
  - board:
      - _(_)
      - x => x + _
    goal:
      - 7
    toolbox:
      - 1
      - 2
      - 3
      - 4
    defines: []
    globals: {}
    textgoal: ''
    note: null
    hiddenGlobals: []
    syntax: []
    autograder:
      inputs: []
      outputs: []
  - board:
      - _(2)
      - _(_)
      - _(_)
      - (x => x + 2)(_)
      - 1
      - 3
    goal:
      - 6
      - 7
    toolbox:
      - number => number + _
      - k => k + 2
      - y => y + 3
      - x => x
    defines: []
    globals: {}
    textgoal: ''
    note: null
    hiddenGlobals: []
    syntax: []
    autograder:
      inputs: []
      outputs: []
